version: '3'
services:
    todo_nginx:
        container_name: todo_nginx
        image: nginx:1.15.6
        ports:
            - '8000:80'
        # depends_on:
        #     - app
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
            # - .:/var/www/html

    todo_app:
        container_name: todo_app
        build: ./docker/php
        volumes:
            - ./:/var/www/html/
        # depends_on:
        #     - mysql

    todo_db:
        container_name: todo_db
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
        - "3306:3306"
#         volumes:
#         - mysql-data:/var/lib/mysql

# volumes:
#     mysql-data:
