version: '3'
services:
    todo-nginx:
        container_name: todo_nginx
        image: nginx:1.15.6
        ports:
            - '8000:80'
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app

    app:
        container_name: app
        build: ./docker/php
        volumes:
            - .:/var/www/html/
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
        - "3306:3306"
        volumes:
        - mysql-data:/var/lib/mysql

volumes:
    mysql-data: